name: ${project.artifactId}Bukkit
main: ${project.groupId}.bukkit.${project.artifactId}Bukkit
version: ${project.version}
author: xXSchrandXx
description: ${project.artifactId}Bukkit
softdepend: [FriendsAPIForPartyAndFriends, PartyAndFriends, PartyAndFriendsGUI]
api-version: 1.13