name: ${project.artifactId}
main: ${project.groupId}.${project.artifactId}
description: ${project.name}
version: ${project.version}
author: xXSchrandXx
website: ${project.url}
database: false
load: STARTUP
softdepend: [FastAsyncWorldEdit, WorldEdit]
loadbefore: [PlotSquared]
commands:
  worldmanager:
    description: Hauptkommando von WorldSystem.
    aliases: [wm]
    usage: /wm <> []